# Generated by Django 5.1.1 on 2024-09-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='child_images/'),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/'),
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parent_images/'),
        ),
    ]
