# Generated by Django 5.1.1 on 2024-09-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_childinfo_user_employeeinfo_user_parentinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfo',
            name='paid',
            field=models.CharField(max_length=50),
        ),
    ]
